uploads = []
generated = []

[[outputs]]
id = "lk4M7nkqeJ1ifsX4-KMS6"
uri = "file://FitPulse.tar.gz"
type = "unspecified"
title = "FitPulse - Source Code"

[[outputs]]
id = "FTSA9_ugwxsWGJSfjEME7"
uri = "file://FitPulse-v2.tar.gz"
type = "unspecified"
title = "FitPulse - Complete Project (Fixed)"

[[outputs]]
id = "fdbD4uJLbgdIlkDPBaC12"
uri = "file://FitPulse-final.tar.gz"
type = "unspecified"
title = "FitPulse - Final Project (Logout Fixed + Change Email)"

[[outputs]]
id = "raZP27i071BewmG5oYORr"
uri = "file://FitPulse.zip"
type = "unspecified"
title = "FitPulse - Complete Project"

[[outputs]]
id = "ymSJUP1s9E6kEchuFrfG1"
uri = "file://FitPulse-Chrome.zip"
type = "unspecified"
title = "FitPulse - Chrome mein chalane ke liye"
