uploads = []
generated = []

[[outputs]]
id = "lk4M7nkqeJ1ifsX4-KMS6"
uri = "file://FitPulse.tar.gz"
type = "unspecified"
title = "FitPulse - Source Code"

[[outputs]]
id = "FTSA9_ugwxsWGJSfjEME7"
uri = "file://FitPulse-v2.tar.gz"
type = "unspecified"
title = "FitPulse - Complete Project (Fixed)"

[[outputs]]
id = "fdbD4uJLbgdIlkDPBaC12"
uri = "file://FitPulse-final.tar.gz"
type = "unspecified"
title = "FitPulse - Final Project (Logout Fixed + Change Email)"

[[outputs]]
id = "raZP27i071BewmG5oYORr"
uri = "file://FitPulse.zip"
type = "unspecified"
title = "FitPulse - Complete Project"

[[outputs]]
id = "ymSJUP1s9E6kEchuFrfG1"
uri = "file://FitPulse-Chrome.zip"
type = "unspecified"
title = "FitPulse - Chrome mein chalane ke liye"

[[outputs]]
id = "CDY1AOGWL_Z47Ry8Pf18M"
uri = "file://FitPulse-Mobile-App.zip"
type = "unspecified"
title = "FitPulse Mobile App - Updated (EAS config + APK guide included)"

[[outputs]]
id = "g1oha1vzHCUFHG_zappMi"
uri = "file://FitPulse-Website.zip"
type = "unspecified"
title = "FitPulse Website - Standalone Source Code (Browser)"

[[outputs]]
id = "Sr2zYRWdLxQN06094SIHG"
uri = "file://FitPulse-Website-Deploy.zip"
type = "unspecified"
title = "FitPulse Website - Deploy ZIP (Render / Railway / Heroku / VPS ready)"

[[outputs]]
id = "wRCu845jETBMcRFtjkpaG"
uri = "file://APK-Build-Share-Guide.txt"
type = "text"
title = "APK Build & Share - Step by Step Guide (Hindi-Urdu)"
